[package]
name = "esc_backend"
version = "0.1.0"
authors = ["caramelmelmel <melody_leong@mymail.sutd.edu.sg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
